# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: liuxinyue
title: Cloud Computing Report
email: 2663182394@qq.com
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  it is about Cloud Computing Report
  

content:
    - title: 实验报告 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 云平台个人博客/网站搭建实验报告
        link: 
        # link_text: Project Website
        additional_links:
          - title:  实验报告链接
            icon: far fa-file-alt
            url: [实验报告链接]
        quote: >
          熟悉使用主流云平台并搭建个人博客或者网站，是云计算时代必备的技能之一。
        description: | # this will include new lines to allow paragraphs
          学号：  202100130052  
          姓名：  刘欣月  
          班级：  21级人工智能  

          实验题目：利用主流云平台搭建个人博客或网站  
          实验学时：2  
          实验日期：  2024.3.27  

          **实验目的：**  
          熟悉使用主流云平台并搭建个人博客或者网站。 具体包括：  

          **参考方案：**  
          基于主流云平台，设计、实现个人博客或者网站的搭建，撰写实验报告（附带网站链接并可以访问），并在网站上呈现此次实验报告。  

          **硬件环境：**  
          联网的计算机一台  

  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
